title: LMIMP
description: ''
social_link: ''
social_username: ''
github_repo: ''
github_username: ''
theme_color: black
remote_theme: mmistakes/jekyll-theme-basically-basic@1.4.5
baseurl: /vokof
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
